# Generated by Django 3.2.7 on 2021-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=10)),
                ('underlying', models.CharField(max_length=3)),
                ('vacine_name', models.CharField(max_length=20)),
                ('vacine_times', models.IntegerField()),
                ('se_code', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'covid',
            },
        ),
    ]
