# Generated by Django 3.2.7 on 2021-11-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servey',
            table='servey',
        ),
    ]
