# Generated by Django 3.2.7 on 2021-11-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_alter_servey_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_effect_code', models.CharField(max_length=1)),
                ('side_effect_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'side_effect',
            },
        ),
        migrations.RenameField(
            model_name='servey',
            old_name='vacine_name',
            new_name='vaccine_name',
        ),
        migrations.RenameField(
            model_name='servey',
            old_name='vacine_times',
            new_name='vaccine_times',
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servey_id', models.ForeignKey(db_column='servey', on_delete=django.db.models.deletion.CASCADE, to='covid.servey')),
                ('side_effect_id', models.ForeignKey(db_column='side_effect', on_delete=django.db.models.deletion.CASCADE, to='covid.sideeffect')),
            ],
            options={
                'db_table': 'match',
            },
        ),
    ]
