# Generated by Django 3.2.7 on 2021-11-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20211118_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=10)),
                ('underlying', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_times', models.IntegerField()),
                ('vaccine_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='covid.user')),
            ],
            options={
                'db_table': 'vaccination',
            },
        ),
        migrations.CreateModel(
            name='VaccinationSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_effect_etc', models.CharField(default=None, max_length=200, null=True)),
                ('side_effect', models.ForeignKey(db_column='side_effect', on_delete=django.db.models.deletion.CASCADE, to='covid.sideeffect')),
                ('vaccination', models.ForeignKey(db_column='vaccination', on_delete=django.db.models.deletion.CASCADE, to='covid.vaccination')),
            ],
            options={
                'db_table': 'vaccination_side_effect',
            },
        ),
        migrations.DeleteModel(
            name='match',
        ),
        migrations.DeleteModel(
            name='Servey',
        ),
    ]
