# Generated by Django 3.2.7 on 2021-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20211118_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='underlying',
            field=models.CharField(max_length=10),
        ),
    ]
