# Generated by Django 3.2.7 on 2021-11-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_alter_user_underlying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationsideeffect',
            name='side_effect',
            field=models.ForeignKey(db_column='side_effect', null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.sideeffect'),
        ),
    ]
